2025-02-11 18:09:18,503 [INFO] 从 https://addressesapi.090227.xyz/cmcc-ipv6 成功抓取到 6 个 IPv6 地址
2025-02-11 18:09:18,516 [WARNING] 获取 2606:4700:3036:6ed4:ff6e:712c:4953:87a5 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:6ed4:ff6e:712c:4953:87a5', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79ed858aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,525 [WARNING] 获取 2606:4700:3036:0:a36a:4af2:65e7:a0d6 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:0:a36a:4af2:65e7:a0d6', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79ed858b30>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,534 [WARNING] 获取 2606:4700:3036:ef:3f32:a9c6:39c4:9ae3 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:ef:3f32:a9c6:39c4:9ae3', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79ed859730>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,541 [WARNING] 获取 2606:4700:3036:ef:db9e:ee41:a8df:d3b2 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:ef:db9e:ee41:a8df:d3b2', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79ed859a90>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,550 [WARNING] 获取 2606:4700:3036:0:a36a:3160:b566:8741 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:0:a36a:3160:b566:8741', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79eda94440>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,556 [WARNING] 获取 2606:4700:3036:6ed4:ffdf:15bf:7d77:5f52 的 colo 信息失败：HTTPConnectionPool(host='2606:4700:3036:6ed4:ffdf:15bf:7d77:5f52', port=80): Max retries exceeded with url: /cdn-cgi/trace (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79ed859cd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-02-11 18:09:18,558 [INFO] 已将处理后的 IPv6 地址写入 speed/cfipv6.txt
2025-02-11 18:09:18,558 [INFO] 检测到内容变更，触发 Git 提交...
